name 'my-machine'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures my-machine'
long_description 'Installs/Configures my-machine'
version '0.1.0'
