name 'my-machine'
maintainer 'Stephen Kershaw'
maintainer_email 'steve@stevek.co.uk'
license 'all_rights'
description 'Installs/Configures my-machine'
long_description 'Installs/Configures my-machine'
version '0.1.0'
